services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatOfficialAccountQrcodeBundle\Command\:
    resource: '../../Command/'
  WechatOfficialAccountQrcodeBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatOfficialAccountQrcodeBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatOfficialAccountQrcodeBundle\Procedure\:
    resource: '../../Procedure/'
  WechatOfficialAccountQrcodeBundle\Repository\:
    resource: '../../Repository/'
  WechatOfficialAccountQrcodeBundle\Service\:
    resource: '../../Service/'
