services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatOfficialAccountQrcodeBundle\AdminMenu: ~

  # 如果确认要使用自动扫描、自动注册，建议尽可能将要扫描的目录路径收缩，不要设置那么大的范围
  WechatOfficialAccountQrcodeBundle\Command\:
    resource: '../../Command/'
  WechatOfficialAccountQrcodeBundle\Controller\:
    resource: '../../Controller/'
  WechatOfficialAccountQrcodeBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatOfficialAccountQrcodeBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatOfficialAccountQrcodeBundle\Procedure\:
    resource: '../../Procedure/'
  WechatOfficialAccountQrcodeBundle\Repository\:
    resource: '../../Repository/'
  WechatOfficialAccountQrcodeBundle\Service\:
    resource: '../../Service/'
