services:
  # default configuration for services in *this* file
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  WechatOfficialAccountQrcodeBundle\Command\:
    resource: '../../Command/'
  WechatOfficialAccountQrcodeBundle\EventSubscriber\:
    resource: '../../EventSubscriber/'
  WechatOfficialAccountQrcodeBundle\MessageHandler\:
    resource: '../../MessageHandler/'
  WechatOfficialAccountQrcodeBundle\Procedure\:
    resource: '../../Procedure/'
  WechatOfficialAccountQrcodeBundle\Repository\:
    resource: '../../Repository/'
  WechatOfficialAccountQrcodeBundle\Controller\:
    resource: '../../Controller/'
    tags: ['controller.service_arguments']
  WechatOfficialAccountQrcodeBundle\Service\:
    resource: '../../Service/'

  # 为监听器注入环境参数
  WechatOfficialAccountQrcodeBundle\EventSubscriber\QrcodeJumpListener:
    arguments:
      $environment: '%kernel.environment%'
