services:
    _defaults:
        autowire: true
        autoconfigure: true

    WechatOfficialAccountQrcodeBundle\DataFixtures\:
        resource: '../../DataFixtures/'
        tags: ['doctrine.fixture.orm']